---
- name: This sets up an httpd webserver
  hosts: localhost
  tasks:
  - name: Install apache packages 
    yum:
      name: localhost
      state: present
  - name: ensure httpd is running
    service:
      name: localhost 
      state: started
